### ISSUE TITLE
[feat] 添加可以一键删除非好友记录的方法

### ISSUE THREAD

**Issue by Timothy-att** [systemannounce/SteamFriends#17]
在哪里加，加什么，加了会怎么样，符合了什么需求。
希望在 好友列表 加入 手动删除记录的选项 加了可以手动删除好友的非朋友记录 自己把好友删除后同样会在下方显示红❌

**Comment by systemannounce** [comment]
> 在哪里加，加什么，加了会怎么样，符合了什么需求。 希望在 好友列表 加入 手动删除记录的选项 加了可以手动删除好友的非朋友记录 自己把好友删除后同样会在下方显示红❌

@Timothy-att 
1. 你是说想要添加一个手动一键清除所有已经被删除的好友记录的方法是吧，就是将所有已经打❌的记录全部删掉，只留下好友的记录？
2. 你自己主动删除的好友也同样会打❌的，因为程序分辨不出来是你删的还是好友删你的。

**Comment by Timothy-att** [comment]
@systemannounce 是的，因为有时候会有些伪装的机器人号来加自己，自己把对面删了后仍会留下记录。
之前倒是把好友列表全部删除再运行一遍删去的好友记录就会一并消失了

**Comment by Timothy-att** [comment]
最后会留下好友的记录，删去的会消失

**Comment by systemannounce** [comment]
现在你更新到最新的仓库代码后，按照这张图操作即可一键自动删除所有非好友记录：
![image](https://github.com/user-attachments/assets/a07ad407-c562-46a8-a0db-ff6b39ff1787)

**Comment by systemannounce** [comment]
试试行不行
@Timothy-att

**Comment by Timothy-att** [comment]
@systemannounce 运行后都是未能启动![image](https://github.com/user-attachments/assets/d6cf6acf-e4a6-4171-a899-174bad6e78df)![image](https://github.com/user-attachments/assets/41a33b9c-5eee-4c0a-9235-d93def6f49d6)

**Comment by systemannounce** [comment]
我刚刚解决了一些语法错误，你现在试试 XD

**Comment by Timothy-att** [comment]
@systemannounce 运行成功了，感谢大佬💗![image](https://github.com/user-attachments/assets/868f108b-5997-4d27-9a54-4856a5d7b152)![image](https://github.com/user-attachments/assets/49aacca0-9955-4ac9-8511-fa859438b955)

**Comment by systemannounce** [comment]
OK
