### ISSUE TITLE
[feat]

### ISSUE THREAD

**Issue by jiucheng02** [systemannounce/SteamFriends#21]
在哪里加，加什么，加了会怎么样，符合了什么需求。

**Comment by systemannounce** [comment]
请描述你的需求……

**Comment by systemannounce** [comment]
![image](https://github.com/user-attachments/assets/69322596-5fc1-4c81-8d0b-441f9e8a5546)
如果是程序问题请看这里的错误提示

**Comment by systemannounce** [comment]
由于长时间不活跃，现关闭issue，如果有需要请新开一个issue。
