### ISSUE TITLE
[feat]大佬，请问这个可不可以看到使用这个项目之前删除我的人

### ISSUE THREAD

**Issue by hc0116** [systemannounce/SteamFriends#23]
如题

**Comment by Timothy-att** [comment]
嗯？你的好友把你删除了，不是一样可以看到吗？（不太理解什么意思👀

**Comment by Timothy-att** [comment]
以前的记录应该看不到吧，这个是从你使用这个项目那一刻开始记录的

**Comment by systemannounce** [comment]
@hc0116 不能，已经删除掉的人除了V社没人可以查到。
这个项目的作用是一个预防作用，在用了这个项目以后所有好友记录的变动程序都会记录下来。
就举个例子，相当于请了个会计记账，没会计以前所有资金流动那就只有天知道了。

**Comment by systemannounce** [comment]
先关闭issue了，如果还有问题可以接着提出，会解答的。
